/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // === remind.u Brand Colors ===
        background: '#E3FDFA',
        surface: '#FFFFFF',
        sidebar: '#DDF5F2',
        primary: '#076559',
        secondary: '#6CA8A5',
        accent: '#B5DBD9',
        success: '#14C97A',
        'text-primary': '#070808',
        'text-secondary': '#635C5D',
        'border-custom': '#D2ECE9',

        // === Material Design Extended Palette ===
        'on-error-container': '#93000a',
        'outline': '#6f7976',
        'on-surface': '#1f1a1b',
        'surface-variant': '#eae0e1',
        'surface-dim': '#e2d8d8',
        'error': '#ba1a1a',
        'surface-container-highest': '#eae0e1',
        'on-tertiary-fixed': '#00201f',
        'primary-fixed': '#a4f1e1',
        'on-primary': '#ffffff',
        'surface-bright': '#fff8f8',
        'tertiary-container': '#3c605f',
        'inverse-primary': '#88d5c5',
        'on-secondary-container': '#306e6b',
        'on-primary-fixed-variant': '#005046',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#c4eae8',
        'on-surface-variant': '#3f4946',
        'on-background': '#1f1a1b',
        'tertiary': '#244847',
        'surface-container-high': '#f0e6e7',
        'on-tertiary-fixed-variant': '#294d4b',
        'secondary-fixed-dim': '#95d2ce',
        'surface-container-low': '#fcf1f2',
        'on-secondary-fixed-variant': '#064f4d',
        'outline-variant': '#bec9c5',
        'on-error': '#ffffff',
        'on-tertiary-container': '#b3d9d7',
        'error-container': '#ffdad6',
        'on-primary-container': '#92dfd0',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#a8cecc',
        'primary-container': '#076559',
        'secondary-fixed': '#b0eeea',
        'inverse-on-surface': '#f9eeef',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#b0eeea',
        'inverse-surface': '#352f30',
        'surface-container': '#f6ebec',
        'on-primary-fixed': '#00201b',
        'on-secondary-fixed': '#00201f',
        'surface-tint': '#126a5e',
        'primary-fixed-dim': '#88d5c5',
        'danger': '#E5484D',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'container-padding-desktop': '32px',
        'base': '8px',
        'container-padding-mobile': '16px',
        'gutter': '24px',
        'sidebar-width': '280px',
      },
      fontFamily: {
        'headline-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
      boxShadow: {
        'level-1': '0 4px 20px rgba(7, 101, 89, 0.08)',
        'level-2': '0 4px 6px -1px rgba(7, 101, 89, 0.12), 0 2px 4px -1px rgba(7, 101, 89, 0.08)',
      },
      keyframes: {
        'pulse-border': {
          '0%': { boxShadow: '0 0 0 0 rgba(186, 26, 26, 0.4)' },
          '70%': { boxShadow: '0 0 0 6px rgba(186, 26, 26, 0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(186, 26, 26, 0)' },
        },
      },
      animation: {
        'pulse-border': 'pulse-border 2s infinite',
      },
    },
  },
  plugins: [],
};
